In [51]:
import pandas as pd

In [52]:
tactics_df = pd.read_csv("../players_db/fm23/tactics_of_teams_fc23.csv").query("fifa_version == 23 and fifa_update == 2")\
                .dropna(axis=1).drop_duplicates(subset=["team_name"], keep="first")
team_df = pd.read_csv("../players_db/fm23/team_ratings.csv")

In [53]:
need_cols = ["team_name", "overall", "attack", "midfield", "defence", 'def_style', 'def_team_width', 'def_team_depth', \
             'off_build_up_play', 'off_chance_creation', 'off_team_width', 'off_players_in_box', 'off_corners', 'off_free_kicks']

build_up_list = tactics_df.off_build_up_play.unique()
off_style_list = tactics_df.off_chance_creation.unique()
def_style_list = tactics_df.def_style.unique()

In [54]:
tactics_merged_df_raw = pd.merge(tactics_df[need_cols], team_df, left_on="team_name", right_on="Club", how="inner")\
                          .dropna(subset=["fbref_name"])
tactics_merged_df = tactics_merged_df_raw.copy()

In [55]:
triple_stats = pd.read_csv("../match_logs/Big5@22-23@triple_stats.csv")

In [56]:
stats_df = pd.merge(tactics_merged_df, triple_stats, left_on="Club", right_on="Club", how="inner")

In [57]:
stats_df.head()

,team_name,overall,attack,midfield,defence,def_style,def_team_width,def_team_depth,off_build_up_play,off_chance_creation,...,Passing,First_Touch,fbref_name,Att_pass,Att_shot,Att_dribble,Total_touches,%pass,%shot,%dribble
0,Liverpool,85,84,82,87,Press After Possession Loss,61.0,71.0,Slow Build Up,Possession,...,85,88,Liverpool,641.078947,15.815789,18.184211,675.078947,0.949636,0.023428,0.026936
1,Manchester City,85,86,86,86,Press After Possession Loss,71.0,81.0,Slow Build Up,Possession,...,90,86,Manchester City,701.105263,15.526316,18.526316,735.157895,0.953680,0.021120,0.025200
2,Real Madrid,85,85,85,84,Balanced,51.0,71.0,Balanced,Balanced,...,92,92,Real Madrid,658.210526,16.684211,25.552632,700.447368,0.939700,0.023819,0.036480
3,Chelsea,84,84,86,84,Balanced,61.0,71.0,Balanced,Balanced,...,74,81,Chelsea,600.947368,12.657895,22.052632,635.657895,0.945394,0.019913,0.034693
4,FC Barcelona,84,84,85,82,Pressure On Heavy Touch,61.0,81.0,Slow Build Up,Possession,...,81,83,Barcelona,650.657895,15.000000,21.078947,686.736842,0.947463,0.021842,0.030694

In [58]:
stats_df[["overall","tpr"]].mean()

overall    76.52
tpr        71.12
dtype: float64

In [59]:
# grp_cols = ["overall","tpr","Total_touches","Att_pass","Att_shot","Att_dribble","%pass","%shot","%dribble"]
grp_cols = ["tpr","Total_touches","%pass","%shot","%dribble"]
query = "tpr != 3270"
stats_df.query(query).shape[0]

75

In [60]:
stats_df.query(query).groupby(by="off_build_up_play").mean(numeric_only=True)[grp_cols]

                         tpr  Total_touches     %pass     %shot  %dribble
off_build_up_play
Balanced           72.600000     512.736904  0.938819  0.024438  0.036742
Fast Build Up      68.368421     488.038340  0.940304  0.023537  0.036160
Long Ball          67.000000     427.311920  0.935344  0.025808  0.038848
Slow Build Up      72.296296     542.956276  0.942290  0.023661  0.034049

In [61]:
stats_df.query(query).groupby(by="off_chance_creation").mean(numeric_only=True)[grp_cols]

                           tpr  Total_touches     %pass     %shot  %dribble
off_chance_creation
Balanced             72.600000     512.736904  0.938819  0.024438  0.036742
Direct Passing       67.000000     427.311920  0.935344  0.025808  0.038848
Forward Runs         68.368421     488.038340  0.940304  0.023537  0.036160
Possession           72.296296     542.956276  0.942290  0.023661  0.034049

In [62]:
stats_df.query(query).groupby(by="def_style").mean(numeric_only=True)[grp_cols]

,tpr,Total_touches,%pass,%shot,%dribble
def_style,,,,,
Balanced,70.619048,507.803648,0.939551,0.024137,0.036312
Press After Possession Loss,73.611111,539.230939,0.941945,0.023747,0.034307
Pressure On Heavy Touch,69.533333,495.087203,0.940219,0.023934,0.035847

In [63]:
column_name = "tpr"
interval_size = 5
min_value = stats_df[column_name].min()
max_value = stats_df[column_name].max()

def group_interval(value, min_val, interval):
    return int((value - min_val) // interval) * interval + min_val

stats_df["group_interval"] = stats_df[column_name].apply(lambda x: group_interval(x, min_value, interval_size))
grouped_df = stats_df.groupby("group_interval").mean(numeric_only=True)[grp_cols]
grouped_df

                      tpr  Total_touches     %pass     %shot  %dribble
group_interval
59              61.000000     444.412281  0.939563  0.022204  0.038234
64              66.300000     476.041277  0.938572  0.024118  0.037311
69              70.312500     489.351393  0.940455  0.024184  0.035361
74              74.642857     537.818885  0.940104  0.024255  0.035641
79              79.000000     579.082486  0.942717  0.024777  0.032506
84              86.000000     674.280702  0.944186  0.021858  0.033956
89              90.500000     705.118421  0.951658  0.022274  0.026068